Repository etianen/logot, pull requests merged in 2024-02, with the labels that each got.

#64 Renamed `_captured` module to `capture`
  logot/__init__.py
  logot/_capture.py
  logot/_logged.py
  logot/_logot.py
Labels: enhancement

#65 Added `release.yml` to improve generated release notes
  .github/release.yml
Labels: documentation

#67 Added external links to documentation sidebar
  docs/index.rst
Labels: documentation

#68 Removing issue tracker link from sidebar
  docs/index.rst
Labels: documentation

#69 Emphasised the synchronous assertions in docs and code
  README.md
  docs/index.rst
  docs/log-capturing.rst
  docs/log-message-matching.rst
  docs/log-pattern-matching.rst
  docs/using-pytest.rst
  docs/using-unittest.rst
  logot/_logot.py
  tests/test_logot.py
Labels: documentation

#78 Added swappable backends for `Logot.wait_for()` and `Logot.await_for()`
  docs/api/logot.asyncio.rst
  docs/api/logot.rst
  docs/index.rst
  docs/using-pytest.rst
  logot/__init__.py
  logot/_asyncio.py
  logot/_import.py
  logot/_logot.py
  logot/_pytest.py
  logot/_typing.py
  logot/_unittest.py
  logot/_wait.py
  logot/asyncio.py
  tests/test_import.py
  tests/test_pytest.py
Labels: enhancement

#95 Renaming `logger` to `name` for `Logot.capturing()`
  docs/log-capturing.rst
  docs/using-pytest.rst
  docs/using-unittest.rst
  logot/_logging.py
  logot/_logot.py
  logot/_loguru.py
  logot/_pytest.py
  logot/_typing.py
  logot/_unittest.py
  logot/_validate.py
  tests/test_logging.py
  tests/test_loguru.py
  tests/test_pytest.py
  tests/test_validate.py
Labels: breaking change

#99 Uploading coverage to codecov
  .codecov.yml
  .github/workflows/build.yml
  README.md
Labels: wontfix

#102 Documenting comparison to ``caplog``
  docs/using-pytest.rst
Labels: documentation

#103 Documenting comparison to ``assertLogs``
  docs/using-pytest.rst
  docs/using-unittest.rst
Labels: documentation

#110 Added `Logot.reduce()` and `Logged.reduce()`
  docs/api/logot.rst
  logot/_logged.py
  logot/_logot.py
  tests/test_logged.py
Labels: enhancement

#109 Added `structlog` support
  .github/workflows/build.yml
  README.md
  docs/api/logot.structlog.rst
  docs/conf.py
  docs/index.rst
  docs/integrations/index.rst
  docs/integrations/structlog.rst
  docs/log-capturing.rst
  docs/using-pytest.rst
  docs/using-unittest.rst
  logot/_structlog.py
  logot/structlog.py
  poetry.lock
  pyproject.toml
  tests/test_structlog.py
Labels: enhancement

#121 Not linking to individual 3rd-party framework integrations
  README.md
  docs/index.rst
  docs/installing.rst
  docs/log-capturing.rst
  docs/using-pytest.rst
  docs/using-unittest.rst
Labels: documentation

#125 Adding top-level docs links to `README`
  README.md
Labels: documentation
